### ISSUE TITLE
Create static  Business Associate Agreement page using new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#12]
### User story
As Loconomics we want our Business Associate Agreement page to have an easy-to-read format to encourage users to understand what they're agreeing to.

#### Tasks
- [x] Create responsive html using Bootstrap 4 and this mockup:
- (awaiting @christinnolasco)
- [x] Implement CSS with Loconomics brand colors
- [ ] Upload necessary assets

**Comment by joshdanielson** [comment]
@IagoSRL I updated this to use the terms photo. We won't have a link to this on the footer but will likely link to it in the app somewhere (TBD). Closing.

**Comment by IagoSRL** [comment]
There is a link to this at the Terms of Service copy (I updated all links yesterday to the new pages), in case that's enough. Happens the same to the #11 and #12 pages.
Thinking if we should have and index page just to list to all this 'legal / terms / policies' pages, just very simple, same format as this but just with a list of h3 headers with links to each one. Or a shared menu in all this pages.

**Comment by joshdanielson** [comment]
Sure! I was thinking that but i don’t think it was in the designs so didn’t want to ask.
