### ISSUE TITLE
Create static home page with new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#4]
### User story
As Loconomics we want our home page to clearly communicate our value propositions to our target user (local service professionals) and motivate them to sign up.

#### Tasks
- [ ] Create responsive html using Bootstrap 4 and this [sketch template](https://www.dropbox.com/s/ejbws8qrolm73i9/Homepage%20%281%29.sketch?dl=0)
- [ ] Implement CSS with Loconomics brand colors
- [ ] Upload necessary assets

**Comment by joshdanielson** [comment]
@tkwok here are the [images and icons](https://www.dropbox.com/sh/w1314n0zuqizkj9/AADuf4CvPzsOxTXLLHUyP3kua?dl=0) for the pages that @christinnolasco chose/created.

**Comment by joshdanielson** [comment]
@tkwok @christinnolasco and I reviewed the site today – great progress! Here are a few comments:
![screencapture-file-users-joshdanielson-downloads-locomotion-frontpage-08-27-18-index-html-2018-08-28-14_13_33](https://user-images.githubusercontent.com/1202838/44751625-8b7c5900-aacd-11e8-980d-6b03f56e1afd.png)
Original design:
![7 25 18 homepage 2](https://user-images.githubusercontent.com/1202838/44751697-bf577e80-aacd-11e8-869e-37dd9baf955d.jpg)

**Comment by joshdanielson** [comment]
@tkwok here is the teal logo: https://www.dropbox.com/s/bi2nyxoelf2h30j/logo-coop.svg?dl=0

**Comment by joshdanielson** [comment]
@christinnolasco here are the employee-owned images that I"m hoping we can work into the footer somewhere: 
[100 Percent Mark.zip](https://github.com/loconomics/loconomics-pages/files/2350156/100.Percent.Mark.zip)

**Comment by christinnolasco** [comment]
@joshdanielson @tkwok Added the 100 Percent Mark in the bottom right corner of the footer.

![9 4 18 home page](https://user-images.githubusercontent.com/39779527/45057720-4024f600-b04b-11e8-9a24-f0abd90723ef.jpg)

**Comment by joshdanielson** [comment]
@tkwok here you can find all the images you need (hero images, etc): https://www.dropbox.com/sh/c3glvih6wjrjpyo/AAD3RS9sDN2N99WJ_T6qmkRPa?dl=0

**Comment by tkwok** [comment]
Thanks for the link Josh. I'll update the static page with this updated
design.

**Comment by IagoSRL** [comment]
Pushed updated styles and markup for the home page, taking care of adjustments for narrow sizes (tablet, phone), so please @joshdanielson review since this details aren't in the design; there are some alternative approaches at some sections but I think the chosen one are the best, but let me know.

Optimized one of the images (it was 20MB!!), need to do the same with the rest (not so large, but still too much for web).
Pending tasks:
- [ ] Didn't touch the footer, that has some things not inline with the design.
- [ ] Behaviors not enabled
  - [ ] Rotate hero image
  - [ ] Enable slideshow (did some initial changes on the existent code but is not ready)
- [ ] Optimize images: crop, rescale and compress. Since they are from stock, they are large
- [ ] Need the final copy, since most are example texts.
  - [x] For the testimonials I have the ones from the current site.
  - [ ] Verify links or expected behaviors for buttons when differ from current site (the 'join us' goes to signup or another thing?)
- [ ] Enable (if isn't) CSS [Autoprefixer for Hugo](https://gohugo.io/hugo-pipes/postcss/#readout), so we really support browsers in our list of supported browsers. Copy browserlist from loconomics app repo.

**Comment by joshdanielson** [comment]
@IagoSRL looks GREAT! The order is perfect. Only thing, aside from your checklist, is the links at the top should be to the right

**Comment by IagoSRL** [comment]
@tkwok Was reviewing your progress at your branch (`tk/static-hugo`) per your comments at Slack. I see only changes at the home page and I found that:
- no one of the pending items is done (see previous two comments here, from @joshdanielson and mine); I didn't expect from you to work on that since I was already on it but knowing that, is clear that working two at the same time on the same files is prone to conflicts
- home was re-refactored as md file plus parametrized partials
  - I may understand the benefit of parametrized if the same large section elements needs to be reused changing copy, but I didn't see that on the designs (I may have forgot something, though, but anyway the sections html size is not that large or complex)
  - I understand how 'data/content focused' looks the new `_index.md` and simple on it's own, at expense to make complex other code, but don't find why is beneficial now rather than move on new pages (OK maybe for future copy updates or let other instances to make their own changes touching the minimal?)
- some copy on the home went to placeholders were some copy was already in place.
- some section content went reverted in styles to originals from static removing my latest work (see services, involved sections).
- at sections were my styles and markup changes were throw away, the CSS and markup errors cross browser and for mobile versions happen again
- the mobile menu is broken now (nothing major, but again don't see the need to change any on it)
- my local changes enter in conflicts because all the file naming, cut and refactor
- just for the record: my work was done on initial code from @tkwok at the static page, moving from a good initial prototype, including some js, into a closer to design layout plus adaptations for mobile, while I tried to do the minimal code changes to go from static to Hugo and updating markup just to make use of less mix of BS styles and less unneeded wrapper elements into a more in control style at a SCSS file per component.

As "bonus tip", don't get the commits that removed and re-added all files, throwing again git history and authorship. If just a mistake on a gitignore happens, just revert back with `git reset HEAD~1` and done, no need to mess up; if the commit was already pushed, going on new branch fixes that. If doubts on something going wrong, just ask and let behave as a team.

--------

I have a flu and just working when feeling a bit better, that is not too much, maybe I'm being bold on this or something and not having the correct mind, sorry if that.

--------

About other things, @joshdanielson I confirmed the wrong aligning you commented on the navbar; it happens on Chrome (sure on Safari too) while on Firefox not, seems a cross browser issue with a flexbox feature.

**Comment by joshdanielson** [comment]
@IagoSRL just reviewed the home page again and added some styling to the "Get involved" section. It's likely not the same CSS standard you're using so apologies. I feel like there probably needs to be some clean-up anyhow with class names and reviewing rem vs. em vs. px: https://webdesign.tutsplus.com/tutorials/comprehensive-guide-when-to-use-em-vs-rem--cms-23984

I also want the second "Become Founding member" button to be the same color as the first but btn-primary or btn-secondary didn't work. 

The other pages seem pretty much perfect. Let me know your thoughts on cleaning up. It's easier since it's only a few pages, and then I can learn the standards you've chosen and adhere to them going forward.

**Comment by IagoSRL** [comment]
@joshdanielson I pushed some minor touch ups at the home and styles, to fix some details as setting a max-width and paddings for the 'hero' (I didn't expected so large texts there before) plus gap with the top on mobile (was overlapping with the navbar on iPhone 6/7/8, SG9 and similar sized devices).

I didn't like the way the overlap is applied at the 'Get Involved' section, because the visual box it creates and the extra limitation of width on the content, but rather than change it I did an alternate so you can review both, just check the `alternate-involved-design` branch. If you choose your current change, I should fix a problem it has with horizontal scrolling at mobile size so let me know.

**Comment by joshdanielson** [comment]
@IagoSRL just reviewed and your 'Get Involved' branch looks great!

**Comment by IagoSRL** [comment]
I moved the CSS units review into it's own issue #21 and a substask about Autoprefixer #22.

@joshdanielson Which links should go on the buttons: "Become funding member", "Refer a pro", "Become a partner".

**Comment by joshdanielson** [comment]
@iagosrl for become founding member, I think we’ll send them to loconomics.coop/signup and for the referral I’m thinking a new page with just our current referral module. For partnering, I was thinking a new page with just a contact us form that sends me an email. I’d like to talk through all with you on a zoom. Are you free tomorrow at 16:30 your time?
