### ISSUE TITLE
Create static About Us page from new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#5]
### User story
As Loconomics we want our about page to clearly communicate our value propositions to our target user (local service professionals) and motivate them to sign up.

#### Tasks
- [ ] Create responsive html using Bootstrap 4 and this mockup:

- [ ] Implement CSS with Loconomics brand colors
- [ ] Upload necessary assets

**Comment by joshdanielson** [comment]
@tkwok here is a link to the images for the "special thanks" section:
https://www.dropbox.com/sh/kl752iozd9rprac/AAASrI6wGUjKlM8Bcpxyb3-Xa?dl=0

**Comment by joshdanielson** [comment]
@tkwok here are the team's photos:
https://www.dropbox.com/sh/kwb2pinprm4ysdm/AAALVvx8Z_tLyIGn6d0pGbl0a?dl=0

**Comment by IagoSRL** [comment]
@joshdanielson Can you send me the 2 top images on this design?

**Comment by joshdanielson** [comment]
@iagosrl they are both in this folder:

https://www.dropbox.com/sh/oybrrjkcap885wx/AAAkfI_d5HrW2P_p8bZNG9-sa?dl=0&m=

**Comment by IagoSRL** [comment]
@joshdanielson the About page is ready to be reviewed, let me know any problem or change (aside the two images from design).
