### ISSUE TITLE
Create static Terms of Service page using new design

### ISSUE THREAD

**Issue by joshdanielson** [loconomics/loconomics-pages#7]
### User story
As Loconomics we want our Terms of Service page to have an easy-to-read format to encourage users to understand what they're agreeing to.

#### Tasks
- [x] Create responsive html using Bootstrap 4 and this mockup:
- (awaiting @christinnolasco)
- [x] Implement CSS with Loconomics brand colors
- [x] Upload necessary assets

**Comment by joshdanielson** [comment]
@tkwok here is the mockup (same for Privacy, Background-check, fees, etc.):
![terms](https://user-images.githubusercontent.com/1202838/44879760-76373400-ac5f-11e8-9525-6760fdc9179d.jpg)

**Comment by IagoSRL** [comment]
@joshdanielson I pushed all the "legal" pages (issues #7, #8, #9, #10, #11, #12), all sharing this styles. Some questions/details:
- Do you want the photo to be the same in all pages?
- There are no links at header or footer to most of this pages, just a 'Terms and Privacy' that I'm not sure which of both pages should link. Go to the /pages/ address to see a list of all pages so you can check them.
- I used html from current site with minor required changes, but please give it a review even if quick.

**Comment by joshdanielson** [comment]
@IagoSRL looks great! I uploaded a photo for this but it needs to be resized. I also updated all the footer links. Some pages will need to be referenced elsewhere (TBD).
Adding the resizing photos task here:
- [ ] resize all new photos uploaded

**Comment by IagoSRL** [comment]
*moved comment, originally posted at #12*

There are links at the Terms of Service copy for the pages #11 #12 #10 (I updated all links yesterday to the new pages), in case that's enough.
Thinking if we should have and index page just to list to all this 'legal / terms / policies' pages, just very simple, same format as this but just with a list of h3 headers with links to each one. Or a shared menu in all this pages.

**Comment by IagoSRL** [comment]
Moved all images used for the 'hero' element into the folder 'hero'. Renamed ones already there with 'home1..2..3', renamed ones that have a meaningful name with that (using ones from @joshdanielson commit messages), updated all links to them.

With that, easier to set-up a common task to optimize that images under the same set of presets (a bit conservative, I think; we may get even further reduction by reducing the height based on current usage). Applied and get a reduction of 83,549.59KB, a lot but because originals are too much big, with metadata and color profile. We ever can recover them from Git history to apply other settings if needed.

**Comment by IagoSRL** [comment]
At QA for a while, I think this is done, closing
